### ISSUE TITLE
Failed to connect to StreamMe

### ISSUE THREAD

**Issue by marpme** [StreamMeBots/stream-me-bot-express#1]
Hey there,

I used your bot API for creating a private chatbot, but actually your bot keeps crashing because it cannot establish a tls connection to stream.me. Could you please review this issue.

![error](https://s.put.re/5yMfyqD.png)

Data that I provided:

```
var bot = new Bot({
    key: "xxxxxxxxxxxxxxx",
    secret: "xxxxxxxxxxxxxxx",
    roomId: "user:46ad6673-ccba-4a67-be94-120dbb2d850e:web",
    debug: true,
});
```

Thank you in advance.

**Comment by wesleytodd** [comment]
Hey @marpme!  Thanks for the interest in our platform.  Unfortunately this chat api has been deprecated.  It is our fault for not updating the readme here to say as much, and I am sorry for that.  We honestly didn't think anyone was using these, or even knew they existed since we don't publicize them.

We are working internally on a whole new and improved public chat api, but it is not ready for prime time yet.  When it is we will publish clients for it on our official @StreamMeDev github org.

Again, sorry for the confusion.
